### ISSUE TITLE
Add pre-upgrade version checks to prevent unsupported upgrade paths

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1064]
We've had a few scenarios where a customer would attempt an upgrade for an unsupported path (e.g. direct 5.0 to 5.5 w/o intermediate runtime) which successfully launched only to fail midway requiring our assistance in rollback.

Gravity should check versions of installed cluster and upgrade and refuse to launch upgrades for unsupported paths. This should be implemented/ported to all current versions.

**Comment by wadells** [comment]
I'd love it if the logic for calculating supported upgrades was modular, such that other tooling (robotest) could use the same logic instead of re-implementing this particular wheel.

**Comment by wadells** [comment]
Also, #940 should be considered when designing these checks, as the work here is likely to increase the number of upgrades that can't be tried at all.

**Comment by wadells** [comment]
> This should be implemented/ported to all current versions.

The more I think about this feature, the less convinced I am that we need to port it to all active branches.  Should this only go into master?

Here's my thinking:  The customers on 5.5 and 6.1 who would hit this likely already have and now understand our supported upgrade policy (via trial by fire).  It is new customers who are more likely to stumble on this, and they'll almost certainly choose to spin up on the most recent release instead of one of the older LTS releases.

Furthermore do we backport features?  I was under the impression that LTS got security patch ports, and maybe a feature that is critical to a paying customer.  Neither this bug and nor the PR #1232 description persuade me that upgrade validation falls into either of those buckets.

**Comment by wadells** [comment]
https://github.com/gravitational/gravity/issues/1735 is a concrete check that we should implement.
