### ISSUE TITLE
Planet container in inconsistent state

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1279]
On multiple occasions we saw running planet container in an inconsistet state:
 * planet (service) user not matching the one from host. For example, the host planet user might have ID `997` and belong to a planet group with ID `994` but inside the container the user would default to planet with stock UID:GID of `1000`:`1000`.
 * `/etc/resolv.conf` is empty inside the container although failure to reflect the host changes are fatal (i.e. the `start` command should be failing if there are errors reflecting the host state)

The latest occurrence is during the upgrade from `5.5.28` -> `5.5.38` where on one of the control nodes the planet container appeared in such state during `system-upgrade` step.

Restart of the container fixes the inconsistency.

We should consider changing upgrade tests to use a custom service user.

**Comment by wadells** [comment]
Are there any logs or snippets of the symptoms that I could look at?  I'm trying to determine the observed impact of this bug, to make sure the test case I'm working on exercises it.

For example is it:

1) Everything in the cluster seems to be working ok after the upgrade, but planet is running under the wrong uid/gid?  No internal conflict, but planet might conflict with another service/user on the system specific to a customer.
2) Planet fails to X because of uid/gid mismatch.  What is X in the logs or `gravity status` output?

**Comment by a-palchikov** [comment]
If the planet container starts with the wrong uid/gid combo, services that run in the context of the service user will fail to read the files.
As an example (also taken from the failed upgrade), is the etcd service (running as service user) that is unable to read its startup configuration (TLS certs/keys). In this case, the automatic upgrade process fails after a timeout.

**Comment by r0mant** [comment]
Closed in https://github.com/gravitational/gravity/pull/1301 (5.5), https://github.com/gravitational/gravity/pull/1306 (6.1), https://github.com/gravitational/gravity/pull/1309 (6.3) and https://github.com/gravitational/gravity/pull/1310 (7.0).
