### ISSUE TITLE
Re-enable nethealth check

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/gravity#1573]
The nethealth check was temporarily disabled while addressing an issue https://github.com/gravitational/gravity/issues/1403. Once the underlying bugs have been addressed and the nethealth check is ready, the nethealth check should be re-enabled as a warning.

**Comment by wadells** [comment]
I found this warning this during 7.0 upgrade testing:

```
Cluster nodes:
    Masters:
        * robotest-77f4cf34-node-0 / 10.138.0.21 / node
            Status:             healthy
            [!]                 overlay packet loss for node robotest-77f4cf34-node-1 is higher than the allowed threshold of 20% (current packet loss at 100%)
            [!]                 overlay packet loss for node robotest-77f4cf34-node-2 is higher than the allowed threshold of 20% (current packet loss at 100%)
            Remote access:      online
        * robotest-77f4cf34-node-1 / 10.138.0.42 / master
            Status:             healthy
            [!]                 overlay packet loss for node robotest-77f4cf34-node-0 is higher than the allowed threshold of 20% (current packet loss at 100%)
            [!]                 overlay packet loss for node robotest-77f4cf34-node-2 is higher than the allowed threshold of 20% (current packet loss at 100%)
            Remote access:      online
        * robotest-77f4cf34-node-2 / 10.138.0.48 / node
            Status:             healthy
            [!]                 overlay packet loss for node robotest-77f4cf34-node-0 is higher than the allowed threshold of 20% (current packet loss at 100%)
            [!]                 overlay packet loss for node robotest-77f4cf34-node-1 is higher than the allowed threshold of 20% (current packet loss at 100%)
```

Is nethealth reenabled as a warning?'

My motivation is: I don't believe that 100% overlay packet loss is a healthy state.  If warning, but otherwise this is reporting healthy is expected behavior for Gravity, then I likely need to update robotest to check for warnings (in addition to degraded status) to make sure we're catching issues like this.

Robotest's current 'looks healthy' validation is:

https://github.com/gravitational/robotest/blob/cc85775c920564666e11d914138bbb330d66ff05/infra/gravity/cluster_status.go#L48-L57
