### ISSUE TITLE
[BUG] Permissions changed in /var/lib/gravity

### ISSUE THREAD

**Issue by tosih** [gravitational/gravity#1710]
**Describe the bug**

After upgrading to Gravity 7.0.7, it seems that some of our tooling broke that interacts with the gravity binary on gravity hosts. The file permissions for /var/lib/gravity have changed so you cannot run the `gravity` binary or `kubectl` without sudo.

**To Reproduce**

```
$ gravity status
[ERROR]: open /var/lib/gravity/local/gravity.db: permission denied
```
```
$ kubectl get pods
error: unable to read client-key /var/lib/gravity/secrets/kubectl.key for default due to open /var/lib/gravity/secrets/kubectl.key: permission denied
```

**Expected behavior**

Both commands above should work without permissions denied.

**Logs**

See above.

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Centos 7.7
 - Gravity [e.g. 5.5.4]: Gravity 7.0.7
 - Platform [e.g. Vmware, AWS]: AWS

**Additional context**

This is a fresh cluster.

**Comment by r0mant** [comment]
I'm pretty sure this is related to the fact that the default gravity system user uid/gid was updated from 1000 to a different number in https://github.com/gravitational/gravity/pull/901 so it's less likely to clash with existing users - which is exactly what was happening before in your systems as 1000 is often a default uid for "centos"/"ubuntu"/etc users. So it's not permissions, but ownership. cc @knisbet 

So I would say this is expected behavior, you can add your host user to the "planet" group which should let it use gravity status without sudo, but I'm not sure it'd let you use kubectl without sudo. Or you could provide `--service-uid=1000`/`--service-gid=1000` flags to the install command if you'd like to keep the old values.

**Comment by tosih** [comment]
Thanks for the quick reply. I'll discuss with my team.

**Comment by r0mant** [comment]
As discussed, closing this one, moving forward with the recommendation of using service uid/gid flags during install.
