### ISSUE TITLE
Add kernel version check

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1818]
Older CentOS/RHEL kernels (in particular, 1092 and earlier) have been known to cause instability and memory allocation failures in some clusters. Satellite should be able to detect the kernel version and trigger a warning if it's one of the affected ones.

More information about the issue, kernel version: https://community.gravitational.com/t/pods-memory-allocation-failures/675.

Success:

- [x] Satellite detects kernels earlier than `3.10.0-1127` and creates a warning.
- [ ] The same kernel check should be executed prior to starting the upgrade (in case the older cluster doesn't have it yet).
  - [ ] This means that there should be some machinery in Gravity that can execute some satellite's preflight checks before triggering an upgrade (so we can potentially plug in some other checks to trigger prior to upgrade).

**Comment by wadells** [comment]
>  The same kernel check should be executed prior to starting the upgrade (in case the older cluster doesn't have it yet). 

Can we run these as pre-install checks too?

At a macro level I care about this, because I've invested several days while executing the 7.0 test plan investigating issues that satellite turned up several minutes after install (or more painfully after a 2nd node joins). 

In terms of feedback loop, install/upgrade is ~5-10 minutes for an empty tarball.  Add in an extra couple for satellite to quiescence and we're showing the users issues 15 minutes (minimum) after they were in a position to make a relevant choice (abort the current upgrade/install, retry on a better kernel).
