### ISSUE TITLE
[Test Plan 7.0 LTS] Upgrade Related Operations

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1823]
# Upgrade Related Operations

### Cluster Upgrade & Join

- [x] Install a 1-node cluster of previous LTS version.
- [x] Upgrade the cluster to the current version.
- [x] Join a master node to the cluster.
  - [x] Verify the node joined successfully.
- [x] Join a regular node to the cluster.
  - [x] Verify the node joined successfully.

### Collecting Garbage

This scenario tests garbage collection on a cluster.

Prerequisites: multi-node cluster with at least 1 regular node. Regular node is necessary to test both master and regular node update paths.

Install a previous LTS version, upgrade to the latest version.

After upgrade execute `gravity gc` on the cluster.

- [x] Verify the operation completes successfully.
 - [x] Verify that packages from the previous installation have been removed locally.
 - [ ] Verify that packages from the previous installation have been removed from cluster package storage.
 - [x] Verify that packages from the current installation are still present.

**Comment by wadells** [comment]
I'm opting not to use a local build of 7.0.x because my upload bandwidth is pitiful and I haven't yet set up a cloud build box.  Thus I'll stick with pre-published artifacts to save hours of fiddling with a build box or pushing bits between my laptop and various clouds.

Validated 6.1.29 OSS -> 7.0.11 OSS on Suse 12 today.  Still reading through the gravity gc source code, grokking what it does (e.g. which directories/systems I need to capture before/after output from to make sure it is doing its job).

**Comment by wadells** [comment]
Done.  The unchecked box is because that step failed, resulting in https://github.com/gravitational/gravity/issues/1850. I'll re-verify once that is fixed.
