### ISSUE TITLE
Gravity 7.0.10, 6.1.x does not install with SELinux enabled

### ISSUE THREAD

**Issue by pablodcar** [gravitational/gravity#2009]
### Description

**What happened**:
When installing gravity in a RHEL 8.1 selinux is enabled by default and the following error appears:

```
[ec2-user@ip-10-1-0-13 installer]$ sudo ./gravity install --advertise-addr=10.1.0.13 --token=secr3t-token --cluster=auto-install-three --cloud-provider=generic --flavor=three --license="$(cat license.pem)"  --role=general_node
Wed Aug 12 18:29:46 UTC	Starting enterprise installer
To abort the installation and clean up the system,
press Ctrl+C two times in a row.
If you get disconnected from the terminal, you can reconnect to the installer
agent by issuing 'gravity resume' command.
If the installation fails, use 'gravity plan' to inspect the state and
'gravity resume' to continue the operation.
See https://gravitational.com/gravity/docs/cluster/#managing-an-ongoing-operation for details.
Wed Aug 12 18:29:47 UTC	Connecting to installer
[ERROR]: error enabling the service
	failed to enable /home/ec2-user/installer/.gravity/gravity-installer.service: Failed to enable unit: Access denied
		exit status 1
```

**What you expected to happen**:
It should install as with gravity 5.5 which works without disabling selinux by hand. Using `setenforce 0` made the install to progress.

**How to reproduce it (as minimally and precisely as possible)**:
Try to install gravity 7.0.10 in a AWS EC2 instance using the AMI RHEL-8.1.0_HVM-20191029-x86_64-0-Hourly2-GP2.

### Environment

 - Gravity version [e.g. 7.0.11]: 7.0.10
 - OS [e.g. Redhat 7.4]: Red Hat 8.1
 - Platform [e.g. Vmware, AWS]: AWS, AMI RHEL-8.1.0_HVM-20191029-x86_64-0-Hourly2-GP2

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
```
status 1 stderr:"Failed to enable unit: Access denied\n" stdout: utils/logging.go:103
2020-08-12T21:15:15Z WARN             Command failed. error:[
ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
	/gopath/src/github.com/gravitational/gravity/lib/utils/exec.go:216 github.com/gravitational/gravity/lib/utils.ExecWithInput
	/gopath/src/github.com/gravitational/gravity/lib/utils/exec.go:182 github.com/gravitational/gravity/lib/utils.Exec
	/gopath/src/github.com/gravitational/gravity/lib/utils/exec.go:170 github.com/gravitational/gravity/lib/utils.ExecL
	/gopath/src/github.com/gravitational/gravity/lib/systemservice/systemd.go:494 github.com/gravitational/gravity/lib/systemservice.invokeSystemctl
	/gopath/src/github.com/gravitational/gravity/lib/systemservice/systemd.go:463 github.com/gravitational/gravity/lib/systemservice.(*systemdManager).EnableService
	/gopath/src/github.com/gravitational/gravity/lib/systemservice/systemd.go:151 github.com/gravitational/gravity/lib/systemservice.(*systemdManager).installService
	/gopath/src/github.com/gravitational/gravity/lib/systemservice/systemd.go:330 github.com/gravitational/gravity/lib/systemservice.(*systemdManager).InstallService
	/gopath/src/github.com/gravitational/gravity/lib/system/service/service.go:121 github.com/gravitational/gravity/lib/system/service.install
	/gopath/src/github.com/gravitational/gravity/lib/system/service/service.go:94 github.com/gravitational/gravity/lib/system/service.Reinstall
	/gopath/src/github.com/gravitational/gravity/lib/install/client/install.go:88 github.com/gravitational/gravity/lib/install/client.(*InstallerStrategy).installSelfAsService
	/gopath/src/github.com/gravitational/gravity/lib/install/client/install.go:47 github.com/gravitational/gravity/lib/install/client.(*InstallerStrategy).connect
	/gopath/src/github.com/gravitational/gravity/lib/install/client/client.go:49 github.com/gravitational/gravity/lib/install/client.New
	/gopath/src/github.com/gravitational/gravity/tool/gravity/cli/install.go:927 github.com/gravitational/gravity/tool/gravity/cli.installerClient
	/gopath/src/github.com/gravitational/gravity/tool/gravity/cli/install.go:712 github.com/gravitational/gravity/tool/gravity/cli.InstallerClient
	/gopath/src/github.com/gravitational/gravity/e/tool/gravity/cli/install.go:45 github.com/gravitational/gravity/e/tool/gravity/cli.startInstall
	/gopath/src/github.com/gravitational/gravity/e/tool/gravity/cli/run.go:91 github.com/gravitational/gravity/e/tool/gravity/cli.execute
	/gopath/src/github.com/gravitational/gravity/e/tool/gravity/cli/run.go:38 github.com/gravitational/gravity/e/tool/gravity/cli.Run
	/gopath/src/github.com/gravitational/gravity/e/tool/gravity/main.go:43 main.run
	/gopath/src/github.com/gravitational/gravity/e/tool/gravity/main.go:27 main.main
	/go/src/runtime/proc.go:200 runtime.main
	/go/src/runtime/asm_amd64.s:1337 runtime.goexit
User Message: error enabling the service
	failed to enable /home/ec2-user/installer/.gravity/gravity-installer.service: Failed to enable unit: Access denied
```

**Comment by a-palchikov** [comment]
`rhel 8` updates the base policy that disables the systemd access to generic user files.
When you extract the installer tarball somewhere under `$HOME`/, the files end up labeled as `user_home_t` and then systemd cannot create/enable the installer service when the gravity install command instructs it to.

I'm not sure how much to invest into fixing this short of forcing SELinux mode on `rhel 8` by default - unfortunately this is complicated if we want the following:
  * installer can be extracted anywhere
  * user wants to use the gravity binary for installation

The problem on SELinux-enabled systems is that there's a certain amount of configuration required to set up the environment in order to be able to install. SELinux support in gravity enables this in the binary itself so it is easier to use (this is what happens when you install with `--selinux`). Unfortunately the SELinux support for `rhel 8` is broken as there are changes between 7 and 8 that need to be taken into consideration and it [has not been done yet](https://github.com/gravitational/gravity/issues/1880#issuecomment-663176575).

If the binary is not SELinux-aware (e.g. when installing without `--selinux`), this preliminary configuration must take place before gravity is invoked (i.e. in a script).
For example, given this script, the installer will work on `rhel 8` as is, without modifications:

```sh
#!/bin/bash
set -Eeou pipefail

scriptdir=$(dirname $(realpath $0))

if [[ $(rpm --queryformat '%{VERSION}' -q redhat-release) =~ "8" ]]; then
  chcon -t systemd_home_t -R "$scriptdir"
  chcon -t bin_t "$scriptdir/gravity"
fi;
"$scriptdir/gravity" "$@"
```
In order to install, one uses `gravity.sh` instead of using the gravity binary directly. This only applies to the installation though - after the cluster has been installed, `gravity` binary can be used as expected.

I'd probably have this script added to the installer tarball with corresponding instructions on proper use and have gravity SELinux support fixed on `rhel 8` in general.

**Comment by a-palchikov** [comment]
Thinking about it some more, I feel that if we always bootstrapped SELinux environment for the installer regardless of whether SELinux was enabled (on a distribution we support that also has SELinux turned on and active) for the installed node, it would simplify things a lot.

**Comment by pablodcar** [comment]
@a-palchikov Thanks for the explanation. Do you know why in gravity 5.5 this is not a problem? Based on your last comment, I guess we can wait for the fix on Gravity 7 before attempting automated redhat 8 installation if it's going to be present in the following weeks.

**Comment by a-palchikov** [comment]
The 5.5.x branch uses a different installer approach. The 6.x branch moved the logic into a service and the service is also configured/namaged in the user directory (relative to the unpacked tarball directory). But the main issue is the involvement of systemd to set up/manage this service which triggers the errors in gravity 6/7.

**Comment by wadells** [comment]
I'll take a look at the 6.1 backport for this, since it ties into my RHEL 8.3 work https://github.com/gravitational/gravity/issues/2331

**Comment by wadells** [comment]
> I'll take a look at the 6.1 backport for this, since it ties into my RHEL 8.3 work #2331

After a discussion with @knisbet today, we've decided not to backport this patchset to Gravity 6.1.x.  We don't presently have any evidence of demand for Gravity 6.1 + Red Hat 8 + SELinux.  Users who are looking for the combination are using 7.0+.  If you want to run Gravity 6.1 on CentOS/RHEL 8 with SELinux enabled, please chime in here to help us gauge interest.
