### ISSUE TITLE
7.0.x wizard installer is failing when node join runs from the same node with installer

### ISSUE THREAD

**Issue by UnderGreen** [gravitational/gravity#2274]
### Description

**What happened**:
Adding a node into the cluster using the same installer node failing with error:
```
[ERROR]: detected an active installer service in /home/ec2-user/.gravity, please resume the agent with `gravity resume` or clean it up using `gravity leave --force` before proceeding (see https://gravitational.com/gravity/docs/cluster/#deleting-a-cluster for more details)
```
**What you expected to happen**:
Node successfully joining.

**How to reproduce it (as minimally and precisely as possible)**:

### Environment

 - Gravity version [e.g. 7.0.11]: 7.0.20
 - OS [e.g. Redhat 7.4]:
 - Platform [e.g. Vmware, AWS]:

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

**Comment by eldios** [comment]
So we found what the problem is.

In recent versions we added a temporary systemd unit that runs the installer and join agent, in order to workaround potential disconnections and sessions issues. So basically the installer/join process is started through a systemd unit (gravity-installer.service or gravity-agent.service).

This systemd unit stores all its data in $HOME/.gravity

In this context when the installer is started, it will create that directory and store its data within it.
Then when the join process starts, it will detect that there's already this directory in place and fail with a "false positive".

The fix should not be too huge... we can probably have it by next Tue/Wed.

**Comment by knisbet** [comment]
So I've been investigating a fix, and I'm not sure how to address it just yet. On the latest 7.0.x as opposed to 7.0.20 there are a couple other glitches to be addressed.

On latest 7.0.x, this error doesn't appear, however the join agent does hang without connecting to the cluster. I'm pretty sure the reason is that the wizard and join agent both self initialize within the current directory, and listen to `./.gravity/installer.sock` which means the wrong PID get's some of the messages.

I tried some basic changes such as renaming the socket, but I think it creates some problems as we don't easily distinguish on whether we want to talk to gravity-agent or the wizard process.

I'm not exactly sure how to avoid this just yet, I see a couple options:
1. Prevent the wizard and join from being started in the same directory, and give a clear warning of what to do. 
2. In the `curl | bash` the wizard provides for join, have that script self-initialize into a temp directory instead of the PWD. The downside is for a user to resume a join they may have to find/switch to the temp directory to find the socket.
3. Have the wizard or gravity agent use a separate socket name/path. I'm not sure to what degree the wizard needs the socket off hand, so it should be safest to move, but my quick attempt to do so broke the startup of the wizard.

@UnderGreen the easiest way to temporarily workaround this issue is to start the join in a different directory from where the wizard was started.

**Comment by r0mant** [comment]
I think option "1" is the simplest to implement and makes sense. I also remember @a-palchikov was mentioning some issues trying to split installer/agent service names - Dim, do you recall what it was, or what's your opinion in general on this issue?

**Comment by a-palchikov** [comment]
The installation on a single node was **never** supposed to use the same directory for installer and agent. When starting the interactive installation, the installer is supposed to be launched from the tarball directory (e.g. the directory where the installer tarball was extracted) while agent needs to start from any other directory except the installer's (tarball's) - they both create and maintain local state which cannot be shared between the two roles.
For example, if the installer has been extracted to `~/installer` it will create a `.gravity` directory inside that directory to persist its state. Once the wizard UI has generated the download link for the agent, it can be started in a separate directory - .e.g. `~/agent` and the cluster can be installed w/o issues:
```
$~ mkdir ~/agent
$~ cd ~/agent
$~/agent curl <agent-download-url> | sudo bash
```

It is true that the state detection might be confusing and does not hint at the possibility of another role (e.g. with installer's state, starting an agent from the same directory or vice versa) clashing with existing state - the message could be updated to reflect that.

**Comment by knisbet** [comment]
> It is true that the state detection might be confusing and does not hint at the possibility of another role (e.g. with installer's state, starting an agent from the same directory or vice versa) clashing with existing state - the message could be updated to reflect that.

Atleast in my testing I don't think builds off the latest version/7.0x commits detect the conflict at all. So we need to fix the detection so we get the message, and yea reword it a bit. This scenario is showing the problem, because the installer is being extracted to the users home directory, so when they login with a second shell and run the `curl | bash` they're naturally in the same directory as the installer.
