### ISSUE TITLE
max master nodes

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#304]
Gravity currently enforces a maximum on master nodes (3), without an apparent way to override.

This creates some implications in a couple cases:
- running 5 etcd nodes is a common operating method, to allow 2 nodes to fail before losing quorum
- When doing node replacements (such as AMI replacement), in some cases it may be preferable to add a node before deleting the node to be replaced. This doesn't really increase the redundancy, because at 4 nodes the cluster can only tolerate one failure, but if the cluster fails to expand it's not left stuck with 2/3 master nodes.

I think gravity should not rewrite master/node membership if explicitly defined in the application manifest, as this may also lead to unexpected behaviour.

Reference: https://github.com/gravitational/gravity/blob/master/lib/ops/opsservice/install.go#L885-L891

**Comment by anandkumarpatel** [comment]
hey, @knisbet we actually need this functionality now that we are doing in place ami updates. We are unable to roll nodes because if we kill the leaders, there are only 2 nodes left which can't do leader election. 
Once that happens node gets into a degraded state and a new master can not join because the cluster is in a degraded state.

**Comment by knisbet** [comment]
This doesn't sound correct to me, if the node is correctly removed from the cluster, I don't believe it should cause the cluster to go into a degraded state. That might be a separate issue from this.

**Comment by anandkumarpatel** [comment]
@knisbet Here are the steps we do to rotate a master node
1. Drain the node
1. Remove node from leader election `etcdctl set ... false`
1. Poll `dig leader.telekube.local` until the node we are removing is not master
1. `gravity remove --force --confirm` node
1. terminate node

we see after we roll all 3 nodes all workers become degraded due to etcd error. Looks like the workers never remove master nodes from their list. These logs loop even after the nodes are long gone. 
```
Jul 22 20:45:36 serf[101]:     2019/07/22 20:45:36 [INFO] agent: Received event: member-join // happens for the first 2 masters
Jul 22 20:45:36 serf[101]:     2019/07/22 20:45:36 [INFO] agent: Received event: member-update
...
Jul 22 20:42:33 etcd[24127]: failed to activate endpoint [10.151.4.172:2379] due to dial tcp 10.151.4.172:2379: connect: connection refused (stay inactive for another 1m0s)
Jul 22 20:42:40 etcd[24127]: failed to activate endpoint [10.151.8.90:2379] due to dial tcp 10.151.8.90:2379: connect: connection timed out (stay inactive for another 1m0s)
```
Then when you roll the last of the orignal 3
```
 etcd collector failed after 5.000170663s: Get https://127.0.0.1:2379/v2/stats/leader: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

The workaround is to remove all worker nodes then a new master is allowed to connect. 
If we have 5 nodes I feel like the above state would not happen since etcd would always have a quorum

**Comment by knisbet** [comment]
@anandkumarpatel I think this is a separate problem from the max number of master nodes and will occur regardless of the number of masters when rotating nodes. I've opened #535 to track this issue.
