### ISSUE TITLE
Issue with cgroup namespaces

### ISSUE THREAD

**Issue by itay** [gravitational/gravity#397]
In newer Gravity builds (5.6.0+), on older kernels (e.g. RHEL7/CentOS7 with kernel 3.10), all preflight checks will succeed but the installer will die in the middle. If you look at `journalctl`, you will see: `cgroup namespaces aren't enabled in the kernel`

This is also mentioned here: https://github.com/gravitational/gravity/pull/372
And is caused by this change: https://github.com/gravitational/planet/pull/397

The ideal fix is to make it not error out in this condition and instead just not use `cgroup namespaces. Alternatively, if that's not possible, it would be good if:

1. Preflight checks didn't pass and made sure it was enabled. This could take the form of https://github.com/opencontainers/runc/blob/master/libcontainer/configs/validate/validator.go#L122

2. The supported OS list was changed to remove RHEL7/CentOS 7.

The impact on us is for now, we've had to downgrade back to 5.5.7 so that we can support those versions.

**Comment by klizhentas** [comment]
thanks for report, it's a known issue and @knisbet was working on the fix AFAIK

**Comment by itay** [comment]
Out of curiosity, is the fix to add it to the preflight check and remove support for RHEL7/CentOS7, or fix by making it not required?

**Comment by knisbet** [comment]
The fix was to disable the cgroup namespace as well as the feature that utilized it on kernels that don't appear to have cgroup namespaces, which was done in https://github.com/gravitational/planet/pull/419.

It looks like the miss was I didn't realize the resource starvation prevention was released with 5.6.0, so I missed the backport to 5.6.0.

**Comment by itay** [comment]
Thanks @knisbet - that’s great.

**Comment by knisbet** [comment]
@itay looks like we may have raced where I edited my last comment. The resource starvation prevention doesn't seem to be on the 5.6.x branch of planet, so I'm a bit confused on how you encountered this issue. Are you building a custom planet or building gravity yourself which would lead you to encounter this?

**Comment by itay** [comment]
As far as I can tell, here is the issue in `planet:

https://github.com/gravitational/planet/blob/5.6.0-11305/lib/box/srv.go#L291

Specifically, the `configs.NEWCGROUP` seems to be appended unconditionally. In 6.0, I believe it is done conditionally:

```	// Cgroup namespaces aren't currently available in redhat/centos based kernels
	// only use cgroup namespaces on kernels that have cgroup namespaces enabled
	cgroupsEnabled, err := CgroupNSEnabled()
	if err != nil {
		return nil, trace.Wrap(err)
	}
	if cgroupsEnabled {
		config.Namespaces = append(config.Namespaces, configs.Namespace{
			Type: configs.NEWCGROUP,
		})
	}```

**Comment by itay** [comment]
Though looking now it may not be in 5.6.1 or 5.6.2, which we hadn't tried to upgrade to (partially because we didn't want to go to Kubernetes 1.14 yet).

**Comment by knisbet** [comment]
Ok, I think I understand. 5.6.0-**11305** wasn't an actual software release. We hadn't decided to create 5.6.0 yet, but with CVE-2019-6486 I needed to tag the master branch of planet so anyone building gravity from master didn't experience a security related regression. This was on Mar 28.

On Apr 8th, we release 5.6.0-**11400** as the 5.6.0 release of gravity with kubernetes 1.14, and swapped master to be a 6.0.x release. So 5.6.0-**11305** was just our master branch, and never part of version/5.6.x. 

I'm going to close this, as it's already been fixed. If you want to be on Kubernetes 1.13, you should be using the 5.5.x release, the only reason to use gravity 5.6 is to get kubernetes 1.14, otherwise it's the same as gravity 5.5.

**Comment by itay** [comment]
Thanks @knisbet - appreciate it! My bad on using a non-version.
