### ISSUE TITLE
Document max number of nodes supported by gravity 5.x.

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#469]
> We are looking at a reasonable number of nodes for Runtime Fabric use cases, I think product engineering tested 16, but I personally think 32 should work fine (5 controller + 27 workers - well beyond any real world use cases as of now). 

A: Theoretically it's limited by etcd/k8s capacity, but would be good to provide some extra info on best practices for scaling apps. 

Note: Also define SSD requirements for running etcd.

**Comment by terrywang** [comment]
I raised this in [slack](https://grv8.slack.com/archives/CEZM4JFDF/p1561599798034500) originally.

Looks like PR #560 fixed the issue, could you please update gravity public docs so that we can validate and refresh / reflect the changes in [Anypoint Runtime Fabric documentation](https://docs.mulesoft.com/runtime-fabric/latest/)?
