### ISSUE TITLE
[BUG] Unable to run privileged containers in docker and k8s

### ISSUE THREAD

**Issue by digger18** [gravitational/gravity#542]
**Describe the bug**
Docker and Kubernetes are unable to run container with **--privileged** permissions, also fails with **--add-cap=ALL**

**To Reproduce**
Inside the planet environment, execute:
```
docker run -it --cap-add=ALL busybox sh
```
OR
```
docker run -it --privileged busybox sh
```

**Expected behavior**
Container to be run with privileged capabilities.

**Logs**
```
gravity-poc-2:/$ docker run -it --cap-add=ALL busybox sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "apply caps: operation not permitted": unknown.
gravity-poc-2:/$ docker run -it --privileged busybox sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "apply caps: operation not permitted": unknown.
```

**Environment:**
 - OS: Ubuntu 18.04
 - Gravity: 6.0.1
 - Platform: GCP

**Additional context**
I also tried this: https://community.gravitational.com/t/can-i-run-privileged-containers-in-gravity/63/3
But the problem is still there.

Note: I must have the ability to use privileged in order to change kernel parameters from inside the container.

**Comment by knisbet** [comment]
As I mentioned in slack over the weekend, because we currently consider privileged containers outside of security best practices and setup kubernetes in a way to prevent privileged containers from running, I'm not sure we should consider the inability to run privileged containers as a bug. 

We may need to re-evaluate this at some point in the future because lots of third-party software doesn't specify narrow permissions and causes friction when trying to run within gravity, but currently this isn't a model we offer support for.

My best guess based on the error is that there is some sort of miss-match in the expected set of capabilities between planet and the host, which is causing runc to throw an error. So digging through runc to see what can lead to an `apply caps:` error is probably the best bet.

**Comment by digger18** [comment]
I believe you are missing the **CAP_AUDIT_READ** here:
https://github.com/gravitational/planet/blob/e89e38d45218a1459c9506e4255726756837cd1b/tool/planet/constants.go#L540

Which leads to a crash when trying to use **--cap-add=ALL** or **--privileged**.

**Comment by digger18** [comment]
Added **CAP_AUDIT_READ** to that file and rebuilt planet from source, now I can run privileged workloads.

**Comment by digger18** [comment]
This works on Ubuntu flawlessly, but on RHEL with an older kernel version it breaks Planet with an  "unknown capability CAP_AUDIT_READ" error.
So the fix must be a bit smarter.

The reason:
https://access.redhat.com/solutions/2834391

**Comment by digger18** [comment]
This patch solved the problem for me:
https://github.com/gravitational/planet/pull/469

Tested on RHEL 7 and Ubuntu 18.04

**Comment by knisbet** [comment]
an allow privileged flag was added in 6.1.4 and 6.0.7 and later releases.

Links:
https://gravitational.com/gravity/docs/changelog/#614-september-9th-2019
https://gravitational.com/gravity/docs/faq/#running-privileged-containers
