### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fywsanshao** [gravitational/gravity#801]
My port 3009 suddenly shut down. How can I restart it?

**Comment by knisbet** [comment]
@fywsanshao for troubleshooting / community support, please direct you're query towards our community forum https://community.gravitational.com/c/gravity which is a more searchable support forum.

In general, for someone to help in troubleshooting, you'll need to provide more details. Standard questions someone might have when helping you:
- What version are you using?
- What makes you think it's not working?
- What specific errors are you seeing?
- Is there anything that makes this setup unique or special?
- Where is it running, in a VM, in a cloud, etc?
- What have you tried to do to isolate the issue? What were the results of what you've tried?
- Any other information you have about the problem?

After troubleshooting and isolating the issue to some degree, if you then believe that this is caused by an issue within gravity itself, the issue tracker on github can be used.
