### ISSUE TITLE
[BUG] `tele build` cannot be used in GitLab CI with Kubernetes

### ISSUE THREAD

**Issue by zimmski** [gravitational/gravity#884]
**Describe the bug**
We are trying to use `tele build` inside of our CI (GitLab with the CI jobs running inside Kubernetes with Docker). However, the following error occurs in step 3 of the build `failed to push images to local registry`.

**To Reproduce**
Use a GitlabCI with Docker and Kubernetes

**Expected behavior**
This should just work. According to https://community.gravitational.com/t/cannot-build-app-tarballs-in-a-docker-container/68/3 the "host" network is needed. In the context of doing the build in Kubernetes, this does not make sense to me.

**Environment (please complete the following information):**
- Gravity 6.2.2

**Comment by militarpancho** [comment]
Hi!, just in case it would be helpful I think that flag is mandatory to tele to build correctly...

**Comment by militarpancho** [comment]
Another problem that I think I've encountered setting gravity with CI is that tele build does not support Docker TCP mode to use dind....I created this pr: https://github.com/gravitational/gravity/pull/886

**Comment by zimmski** [comment]
Thanks for your answer. I will definitely have a look at your PR.

What I am wondering is why the "host" network is needed at all and how Gravity can be changed to simply not require this option anymore.

**Comment by militarpancho** [comment]
I think the reason is performance...a lot of ports are used to vendor docker images detected in the yaml resources at build time. If your CI is running in Kubernetes, using dind instead of the unix socket in the same pod that the container that runs "tele" could avoid "host" flag to be needed.... (I suppose this because containers in the same pod shares network port space)
