### ISSUE TITLE
Join on AWS inconsistently fails when pulling large packages via ELB

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#931]
### Scenario:

* Installing a cluster on AWS, with cloud integration enabled.
* Install 1 node.
* Start joining other nodes.
* Sometimes, the join fails on "pull" phase with `unexpected EOF` error when trying to pull a large application package from master via ELB that points to gravity-site:

```
[centos@ip-10-1-0-77 ~]$ gravity --insecure package pull gravitational.io/opscenter:0.0.12-30-g1794dc2 --ops-url=https://internal-a46529de8011047b0a35c839f3acdef7-267369847.us-east-1.elb.amazonaws.com:3009 --force
[=>                                                                                                  ] 17MB/1.3GB[ERROR]: unexpected EOF
```

* When pulling directly from the node (not via ELB), it worked:

```
[centos@ip-10-1-0-77 ~]$ gravity --insecure package pull gravitational.io/opscenter:0.0.12-30-g1794dc2 --ops-url=https://10.1.2.161:3009 --force
[====================================================================================================] 1.3GB/1.3GBB
transfer completed
gravitational.io/opscenter:0.0.12-30-g1794dc2 pulled from https://10.1.2.161:3009
```

### Additional details:

* The cluster image that was having this issue was built the following way:
  * `tele pull opscenter:xxx`.
  * Unpack/modify app.yaml inside it.
  * `tele build` it back.

This resulted into the entire installer being packaged as the application resources so all packages were essentially present in the resulting cluster image twice and the `opscenter` package alone was 1.3GB. The pull was failing when trying to pull this package.

* gravity-site service currently uses Classic LB. When changing LB type to Network LB (newer type, not supported by all instance types), it worked.

* Captured `tcpdump` on both client/server sides showed fin/ack initiated by the load balancer and in `gravity-site` logs there is an error `connection reset by peer`.

### Theories:

It's not clear why EOF is happening, it also happens inconsistently i.e. it may not work for a few times and then start consistently working.

* Large package size?
* Bad byte stream due to the way it was packaged?
* Bad infra on this particular AWS account?

### Action items:

We should see if we can reproduce it in our infrastructure:

* Build the cluster image the same way, to produce a large package.
* Try to expand by using `internal-xxx` load balancer as a peer for the join command.
* See if it's size related (i.e. create more large packages and try to pull them) or not.

**Comment by a-palchikov** [comment]
Relevant: https://github.com/go-sql-driver/mysql/issues/674#issuecomment-345661869

**Comment by knisbet** [comment]
I was reading through the ticket Dima referenced, and I think I have a theory about what could've happened. 

Looking at the screenshot of server -> LB, it looks like traffic for server to LB stalled for atleast 1 second due to the window being full. This means the LB application itself didn't read any data from the socket for atleast 1 second. If the idle timeout is directional based on the server -> client, and does default to 1 second, the application could've detected this as an idle connection and terminated the connection, as no data was read from the server socket for just over 1 second.

I don't remember the equivalent capture of LB -> client, but if it was progressing too slowly due to disk writes (due to the particular file transfer being 1GB), it's possible it wasn't draining the LB fast enough, allowing the server -> LB to go idle for 1 second. I would need the original PCAP's for the same attempt from both sides of the LB to verify this theory, but it seems plausible.

**Comment by r0mant** [comment]
@knisbet Sure, I still have the original pcaps, didn't attach them to the ticket b/c one of them is 600MB. I could upload them somewhere and share with you. The theory of a slow LB makes sense, although we do set the idle timeout connection to 3600 seconds on the load balancers.
