### ISSUE TITLE
Gravity missing required fields when registering a node

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#993]
There was recently a change that disabled automatic node registration in kubelet b/c starting with 1.16(?) kubelet is not allowed to set certain labels on the nodes by itself, due to security reasons. The change, instead, moved the responsibility of registering the nodes onto Gravity so it creates the node objects itself during one of the install phases.

This approach started costing us a bunch of regressions b/c kubelet does all sorts of logic when registering a node, which Gravity does not. One issue encountered in the past is that kubelet sets certain annotations on the nodes. The most recent issue is `spec.providerID` field that kubelet sets when cloud-integration is enabled - w/o it the load balancers don't work properly.

We have 2 ways forward:

1. Have Gravity set `spec.providerID` duplicating kubelet's logic. My concern is that these sorts of issues will keep happening, esp. with upgrades to new versions when kubelet logic changes.
2. Restore the automatic node registration and instead of having Gravity register the entire node object, just set the appropriate labels/taints that kubelet cannot set itself.

I'm leaning towards option number 2. I'm pretty sure this will save us a lot of headache in the future.

@a-palchikov @knisbet What do you guys think?

**Comment by a-palchikov** [comment]
It definitely looks like kubelet has a fair share of logic for [setting up](https://github.com/kubernetes/kubernetes/blob/v1.15.5/pkg/kubelet/kubelet_node_status.go#L217) a node object. While this could be replicated, I agree with @r0mant that it then should either be done with each release or we let kubelet set the node up with the list of labels it is allowed to set while setting the rest externally my updating the node object.

**Comment by knisbet** [comment]
Hmmm, so part of the original motivation for going this direction was due to the actual problem, where kubelet implements it's own label validation logic that differs from kubernetes itself. However, a second component to be considered, is it sounded to me like kubelet / kubeneretes may be heading in this direction anyways. The security risk with the automatic registration process, is that a compromised nodes might be able to affect it's labels to get workloads assigned that would not normally be assigned to the particular node. Although I'm not sure where that currently stands, and it did look like a much more complicated mechanism was going to be in place on which labels / taints can be controlled by kubelet, and filter to specific fields that cannot.

So I'm not opposed in any way with option 2, we just need to be weary of if the node object is inadvertently deleted it will only partially be re-created, and that long term we may be driven back towards the current registration process. Doesn't mean we shouldn't avoid some short term pain points though.

**Comment by helgi** [comment]
Probably can be closed at this point unless what @knisbet is something to consider as newer k8s versions come out.
